import { API_URL } from "../config.ts";
import axios from "axios";

const createAxiosInstance = (baseURL: string) => {
  const instance = axios.create({
    baseURL,
    timeout: 10000, // 请求超时设置为10秒
  });

  // set token
  instance.interceptors.request.use(
    (config) => {
      const token =
        localStorage.getItem("token") ||
        "eyJhbGciOiJSUzI1NiIsInR5cCI6IkpXVCIsImtpZCI6IlBMY2xEOFFuUnpqMFBZOEN1OEFFSiJ9.eyJodHRwczovL2VycC50aGVwaWxhYi5jb20vcm9sZXMiOlsiT3duZXIiLCJBY2FkZW1pYyBTdXBwb3J0Il0sInVzZXJSb2xlcyI6WyJPd25lciIsIkFjYWRlbWljIFN1cHBvcnQiXSwidXNlck1ldGFkYXRhIjp7fSwiaXNzIjoiaHR0cHM6Ly90aGVwaWxhYi5hdS5hdXRoMC5jb20vIiwic3ViIjoiYXV0aDB8NjY0NWFhZDA5YWNiZWM1MjRhMjc3YTViIiwiYXVkIjpbImh0dHBzOi8vZXJwLnRoZXBpbGFiLmNvbSIsImh0dHBzOi8vdGhlcGlsYWIuYXUuYXV0aDAuY29tL3VzZXJpbmZvIl0sImlhdCI6MTcxODI0OTMwMCwiZXhwIjoxNzE4MzM1NzAwLCJzY29wZSI6Im9wZW5pZCBwcm9maWxlIGVtYWlsIG9mZmxpbmVfYWNjZXNzIiwib3JnX2lkIjoib3JnXzhFcUJhOWk1eENWRW55Y3UiLCJhenAiOiJtakRGZHdpaVBTalRONXBmbnVzRFB6UFNXRjBzZjZwYSIsInBlcm1pc3Npb25zIjpbImFjYWRlbWljLWxldmVsOnVwZGF0ZSIsImFjYWRlbWljLWxldmVsOnZpZXciLCJhY2FkZW1pYy15ZWFyOnVwZGF0ZSIsImFjYWRlbWljLXllYXI6dmlldyIsImFyY2h1cy1hY2FkZW1pYzphY2Nlc3MiLCJhcmNodXM6YWNjZXNzIiwiYXJjaHVzLWFkbWluaXN0cmF0aW9uOmFjY2VzcyIsImFyY2h1cy1jY2M6YWNjZXNzIiwiYXJjaHVzLWNybTphY2Nlc3MiLCJhcmNodXMtbm90ZXM6YWNjZXNzIiwiYXJyYW5nZW1lbnQ6dXBkYXRlIiwiYXJyYW5nZW1lbnQ6dmlldyIsImFycmFuZ2VtZW50OnZpZXc6ZXhwb3J0IiwiYXR0ZW5kYW5jZTp1cGRhdGUiLCJhdHRlbmRhbmNlOnZpZXciLCJiYWxhbmNlOnVwZGF0ZSIsImJyYW5jaDp1cGRhdGUiLCJicmFuY2g6dmlldyIsImNhbXBhaWduOnVwZGF0ZSIsImNhbXBhaWduOnZpZXciLCJjYW1wYWlnbjp2aWV3OmV4cG9ydCIsImNsYXNzOnVwZGF0ZSIsImNsYXNzOnZpZXciLCJjbGFzczp2aWV3OmV4cG9ydCIsImNvbGxlY3Q6dXBkYXRlIiwiY29sbGVjdDp2aWV3IiwiY291cnNlLWVsaWdpYmlsaXR5OnVwZGF0ZSIsImNvdXJzZS1lbGlnaWJpbGl0eTp2aWV3IiwiY291cnNlLW5vdGlmaWNhdGlvbi1saXN0OnVwZGF0ZSIsImNvdXJzZS1ub3RpZmljYXRpb24tbGlzdDp2aWV3IiwiY291cnNlOnVwZGF0ZSIsImNvdXJzZTp2aWV3IiwiY291cnNlOnZpZXc6ZXhwb3J0IiwiZGVsaXZlcnk6dXBkYXRlIiwiZGVsaXZlcnk6dmlldyIsImRlcGFydG1lbnQ6dXBkYXRlIiwiZGVwYXJ0bWVudDp2aWV3IiwiZW5yb2xsbWVudDp2aWV3IiwiZXhlcmNpc2U6dXBkYXRlIiwiZXhlcmNpc2U6dmlldyIsImZlYXR1cmU6dXBkYXRlIiwiZmVhdHVyZTp2aWV3IiwiZmVlZGJhY2s6dXBkYXRlIiwiZmVlZGJhY2s6dmlldyIsImdyb3VwLWFzc2lnbm1lbnQ6dXBkYXRlIiwiZ3JvdXAtYXNzaWdubWVudDp2aWV3IiwiaG9saWRheTp1cGRhdGUiLCJob2xpZGF5OnZpZXciLCJob21ld29yazp1cGRhdGUiLCJob21ld29yazp2aWV3IiwiaW50ZWdyYXRpb246dXBkYXRlIiwiaW50ZWdyYXRpb246dmlldyIsImludm9pY2U6dXBkYXRlIiwiaW52b2ljZTp2aWV3IiwiaW52b2ljZTp2aWV3OmV4cG9ydCIsImxlc3Nvbi1wbGFuOnVwZGF0ZSIsImxlc3Nvbi1wbGFuOnZpZXciLCJsZXNzb246dXBkYXRlIiwibGVzc29uOnZpZXciLCJsZXNzb246dmlldzpleHBvcnQiLCJtYXRlcmlhbDp1cGRhdGUiLCJtYXRlcmlhbDp2aWV3Iiwibm90aWZpY2F0aW9uLWxvZzp1cGRhdGUiLCJub3RpZmljYXRpb24tbG9nOnZpZXciLCJwYWNraW5nLWxpc3Q6dXBkYXRlIiwicGFja2luZy1saXN0OnZpZXciLCJwYXJlbnQ6dXBkYXRlIiwicGFyZW50OnZpZXciLCJwYXJlbnQ6dmlldzpleHBvcnQiLCJwYXltZW50OnVwZGF0ZSIsInBheW1lbnQ6dmlldyIsInBlcm1pc3Npb246dmlldyIsInByb21vdGlvbjp1cGRhdGUiLCJwcm9tb3Rpb246dmlldyIsInJlY2VpcHQ6dmlldyIsInJlY2VpcHQ6dmlldzpleHBvcnQiLCJyZWZlcmVuY2UtZGF0YTp1cGRhdGUiLCJyZWZlcmVuY2UtZGF0YTp2aWV3IiwicmVmdW5kOnVwZGF0ZSIsInJlZnVuZDp2aWV3IiwicmVmdW5kOnZpZXc6ZXhwb3J0IiwicmVnaXN0cmF0aW9uOnVwZGF0ZSIsInJlZ2lzdHJhdGlvbjp2aWV3IiwicmVnaXN0cmF0aW9uOnZpZXc6ZXhwb3J0IiwicmVtYXJrczp1cGRhdGUiLCJyZW1hcmtzOnZpZXciLCJyZXBvcnQtYXR0ZW5kYW5jZTp2aWV3IiwicmVwb3J0LWF0dGVuZGFuY2U6dmlldzpleHBvcnQiLCJyZXBvcnQtaW52b2ljZTp2aWV3IiwicmVwb3J0LWludm9pY2U6dmlldzpleHBvcnQiLCJyZXBvcnQtcGF5bWVudDp2aWV3IiwicmVwb3J0LXBheW1lbnQ6dmlldzpleHBvcnQiLCJyZXBvcnQtcmV2ZW51ZTp2aWV3IiwicmVwb3J0LXJldmVudWU6dmlldzpleHBvcnQiLCJyZXdhcmQ6dXBkYXRlIiwicmV3YXJkOnZpZXciLCJyb2xlOnVwZGF0ZSIsInJvbGU6dmlldyIsInNjaG9vbDp1cGRhdGUiLCJzY2hvb2w6dmlldyIsInN0YXRlbWVudC1vZi1hY2NvdW50OnZpZXciLCJzdGF0ZW1lbnQtb2YtYWNjb3VudDp2aWV3OmV4cG9ydCIsInN0dWRlbnQ6dXBkYXRlIiwic3R1ZGVudDp2aWV3Iiwic3R1ZGVudDp2aWV3OmV4cG9ydCIsInN1aXRhYmlsaXR5OnVwZGF0ZSIsInN5c3RlbS11c2VyOnVwZGF0ZSIsInN5c3RlbS11c2VyOnZpZXciLCJzeXN0ZW0tdXNlcjp2aWV3OmV4cG9ydCIsInRhc2s6dXBkYXRlIiwidGFzazp2aWV3IiwidGVtcGxhdGU6dXBkYXRlIiwidGVtcGxhdGU6dmlldyIsInRlcm0tYmlsbGluZy1kdWUtZGF0ZTp1cGRhdGUiLCJ0ZXJtLWJpbGxpbmctZHVlLWRhdGU6dmlldyIsInRvcGljOmNyZWF0ZSIsInVzZXItcmVxdWVzdC1wYXltZW50OnVwZGF0ZSIsInVzZXItcmVxdWVzdC1wYXltZW50OnZpZXciLCJ1c2VyLXJlcXVlc3Q6dXBkYXRlIiwidXNlci1yZXF1ZXN0OnZpZXciLCJ2ZW51ZTp1cGRhdGUiLCJ2ZW51ZTp2aWV3Iiwid2hhdHNhcHAtYWNjb3VudDp1cGRhdGUiLCJ3aGF0c2FwcC1hY2NvdW50OnZpZXciLCJ3aGF0c2FwcC1tZXNzYWdlOnVwZGF0ZSIsIndoYXRzYXBwLW1lc3NhZ2U6dmlldyIsIndvcmtzaGVldDp1cGRhdGUiLCJ3b3Jrc2hlZXQ6dmlldyIsIndvcmtzaGVldDp2aWV3OmV4cG9ydCJdfQ.K8hXn-gxUo-DAGROOyMONugYQeQ3UZaHogPoMMKR_df_QqvocqJGwcziPhk3CF0pHRQeTpzvidDWdsHeK0UKhKIZkFdG7Da6VSJCOcr9QBKpzAOG99DAh4miZB9v_nwDhhH9x4jaN2bNGDmXpgtZbXER6-R2B9VwBHW2gdhcdO2PRggXeJU76S23TwZHe2wWbq7rGS8OPL_3lBFJVRETARAi_l0AcUuGYYiYiks90Yp-qD1H0CFtP8jZL5H_oFDpYETN6IHW_x_ZSaVP27tG-x---lR8dtmKLDcHzvooaFISO0vANCLlrFmJ6BUNa2PFVAluCUzkDOhNm7bskUMbMQ";
      if (token) {
        config.headers.Authorization = `Bearer ${token}`;
      }
      return config;
    },
    (error) => Promise.reject(error),
  );

  // 响应拦截器
  instance.interceptors.response.use(
    (response) => response,
    (error) => {
      if (error.response) {
        // 请求已发出，但服务器响应状态码不在2xx范围内
        console.error("Error Response:", error.response);
      } else if (error.request) {
        // 请求已发出，但没有收到响应
        console.error("Error Request:", error.request);
      } else {
        // 其他错误
        console.error("Error Message:", error.message);
      }
      return Promise.reject(error);
    },
  );

  return instance;
};

// 创建不同后端服务的 Axios 实例
const client = createAxiosInstance(API_URL);

const fetcher = (url: string) => client.get(url).then((res) => res.data.data);

export { client, fetcher };
